### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by isidentical** [coogger/coogger#66] opened 2019-04-15 16:51 UTC
Coogger can use badges like discord's role system. Every user earns badges in specific actions like 10th post, 25th post, 50th post or when contributed to coogger. It motivates users to contribute / use coogger more.

**Comment by hakancelik96** [comment] 2019-04-15 16:59
Good issue if you want to this feature, you can develop as you can say, of course, if you don't want for wait for me

**Comment by BTaskaya** [comment] 2019-04-15 16:59
You can assign it to me, thanks.

**Comment by BTaskaya** [comment] 2019-04-16 16:42
I'm leaving the issue because the issue is not fully understood by maintainers.

**Comment by hakancelik96** [comment] 2019-07-16 13:41
badge feature added but auto badge assignment is not currently done, this is inside in TODO

**Comment by hakancelik96** [comment] 2019-07-20 21:04
https://github.com/coogger/coogger/commit/fbe0ea9cf8e0161f37289e59ad393cb4760d8423

https://github.com/coogger/coogger/commit/7dda58db1c46b09ec3c472d273314de812c2f799

https://github.com/coogger/coogger/commit/1733a377d7909793862222ea26855b0a87628e4e

**Closed by hakancelik96** 2019-07-20 21:04 UTC
Labels: help wanted
